### ISSUE TITLE
[feat] Direct file output for LLM responses

### ISSUE THREAD

**Issue by PeterDaveHello** [simonmysun/ell#15]
Hi,

First, this project is cool! The command-line interface for LLMs is handy.

I wonder if you would consider adding a feature to write LLM output directly into a file? This could be very helpful for users who want to save responses for later reference, processing, or as a final result of their interaction with the LLM.

A possible implementation could be a command-line option like `-o filename.txt` or `--output filename.txt`.

Thank you for your great work and for considering this suggestion.

**Comment by simonmysun** [comment]
Thank you for your appreciation! 

If you want to save to a file, you can redirect stdout or pipe the output to `tee`, depending on you want to see the result in your terminal or not. 

```bash
ell "What is the capital of France" | tee result.txt
```

or if you simply don't need the result to be shown in your terminal:

```bash
ell "What is the capital of France" > result.txt
```

But adding another option for output is also a good idea. This will allow user to have more flexibility. Thank you for the suggestion!

**Comment by PeterDaveHello** [comment]
Yeah, it's not too complex to do the pipe things manually :laughing: but an option would also be great :smile:

**Comment by simonmysun** [comment]
Question: What's the expected behaviour in record and interactive mode?

**Comment by PeterDaveHello** [comment]
Thanks for considering the feature! How about we record both the input and output of the LLM in both record and interactive modes? What do you think?

**Comment by simonmysun** [comment]
Implemented.
