### ISSUE TITLE
Template not found: ~/.ellrc.d/templates/default-gemini.json

### ISSUE THREAD

**Issue by michaelnew** [simonmysun/ell#16]
Looks like the `~` character is not being expanded on line 23 of `ell.sh`, preventing the script from finding `default-gemini.json`:
`: "${ELL_TEMPLATE_PATH:=~/.ellrc.d/templates/}";`
If I change that line to:
`: "${ELL_TEMPLATE_PATH:=$HOME/.ellrc.d/templates/}";`
it works fine.

I'm using zsh FWIW. Not sure if that's a factor.

**Comment by simonmysun** [comment]
Hi, thanks for reporting. Sorry for the delay. I was too confused on shell expansions.
